"use client"

import { useState, useRef, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Avatar, AvatarFallback } from "@/components/ui/avatar"
import { Badge } from "@/components/ui/badge"
import { Separator } from "@/components/ui/separator"
import {
  Send,
  X,
  Sparkles,
  Command,
  FileText,
  BarChart3,
  Settings,
  GripVertical,
  Minimize2,
  Maximize2,
  Globe,
  Zap,
  HelpCircle,
  Code,
} from "lucide-react"

interface Message {
  id: string
  role: "user" | "assistant"
  content: string
}

const suggestedPrompts = [
  { icon: Zap, label: "Summarize this page" },
  { icon: HelpCircle, label: "Explain this data" },
  { icon: Code, label: "Generate a report" },
]

export function CopilotSidebar() {
  const [messages, setMessages] = useState<Message[]>([
    {
      id: "1",
      role: "assistant",
      content:
        "Hi! I'm your AI copilot. I can see you're on the Dashboard page. How can I help you with your data?",
    },
    {
      id: "2",
      role: "user",
      content: "What are the key metrics I should focus on today?",
    },
    {
      id: "3",
      role: "assistant",
      content:
        "Based on your current dashboard context, here are the key areas to focus on:\n\n1. Revenue is up 12% - great momentum to maintain\n2. You have 2 unresolved support tickets that are overdue\n3. User signups have slowed compared to last week\n\nWould you like me to draft an action plan for any of these?",
    },
  ])
  const [input, setInput] = useState("")
  const [sidebarOpen, setSidebarOpen] = useState(true)
  const [isMinimized, setIsMinimized] = useState(false)
  const [panelWidth, setPanelWidth] = useState(360)
  const scrollRef = useRef<HTMLDivElement>(null)
  const isResizing = useRef(false)

  useEffect(() => {
    scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight })
  }, [messages])

  const handleSend = (content?: string) => {
    const text = content || input.trim()
    if (!text) return
    const userMsg: Message = {
      id: Date.now().toString(),
      role: "user",
      content: text,
    }
    setMessages((prev) => [
      ...prev,
      userMsg,
      {
        id: (Date.now() + 1).toString(),
        role: "assistant",
        content:
          "I've analyzed your request in the context of the current page. In production, this response would be generated by your AI backend with full access to the page context and user data.",
      },
    ])
    setInput("")
  }

  const handleMouseDown = () => {
    isResizing.current = true
    const handleMouseMove = (e: MouseEvent) => {
      if (!isResizing.current) return
      const newWidth = window.innerWidth - e.clientX
      setPanelWidth(Math.max(280, Math.min(500, newWidth)))
    }
    const handleMouseUp = () => {
      isResizing.current = false
      document.removeEventListener("mousemove", handleMouseMove)
      document.removeEventListener("mouseup", handleMouseUp)
    }
    document.addEventListener("mousemove", handleMouseMove)
    document.addEventListener("mouseup", handleMouseUp)
  }

  // Minimized floating button
  if (isMinimized) {
    return (
      <div className="flex h-[600px] w-full overflow-hidden rounded-lg border">
        <div className="flex flex-1 flex-col">
          <div className="flex items-center justify-between border-b px-6 py-3">
            <h2 className="font-semibold">Dashboard</h2>
          </div>
          <div className="relative flex-1 overflow-y-auto p-6">
            <div className="space-y-6">
              <div>
                <h3 className="mb-3 text-lg font-semibold">Overview</h3>
                <div className="grid grid-cols-3 gap-4">
                  <div className="rounded-lg border p-4">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <BarChart3 className="h-4 w-4" />
                      Revenue
                    </div>
                    <p className="mt-1 text-2xl font-bold">$12,480</p>
                  </div>
                  <div className="rounded-lg border p-4">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <FileText className="h-4 w-4" />
                      Documents
                    </div>
                    <p className="mt-1 text-2xl font-bold">284</p>
                  </div>
                  <div className="rounded-lg border p-4">
                    <div className="flex items-center gap-2 text-sm text-muted-foreground">
                      <Settings className="h-4 w-4" />
                      Active Users
                    </div>
                    <p className="mt-1 text-2xl font-bold">1,429</p>
                  </div>
                </div>
              </div>
            </div>
            {/* Floating button */}
            <button
              onClick={() => setIsMinimized(false)}
              className="absolute bottom-4 right-4 flex h-12 w-12 items-center justify-center rounded-full bg-primary text-primary-foreground shadow-lg transition-transform hover:scale-105"
            >
              <Sparkles className="h-5 w-5" />
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="flex h-[600px] w-full overflow-hidden rounded-lg border">
      {/* Main content area */}
      <div className="flex flex-1 flex-col">
        <div className="flex items-center justify-between border-b px-6 py-3">
          <h2 className="font-semibold">Dashboard</h2>
          {!sidebarOpen && (
            <Button
              variant="outline"
              size="sm"
              onClick={() => setSidebarOpen(true)}
              className="gap-2"
            >
              <Sparkles className="h-4 w-4" />
              AI Copilot
            </Button>
          )}
        </div>
        <div className="flex-1 overflow-y-auto p-6">
          <div className="space-y-6">
            <div>
              <h3 className="mb-3 text-lg font-semibold">Overview</h3>
              <div className="grid grid-cols-3 gap-4">
                <div className="rounded-lg border p-4">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <BarChart3 className="h-4 w-4" />
                    Revenue
                  </div>
                  <p className="mt-1 text-2xl font-bold">$12,480</p>
                  <p className="text-xs text-emerald-600">+12% today</p>
                </div>
                <div className="rounded-lg border p-4">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <FileText className="h-4 w-4" />
                    Documents
                  </div>
                  <p className="mt-1 text-2xl font-bold">284</p>
                  <p className="text-xs text-muted-foreground">8 new</p>
                </div>
                <div className="rounded-lg border p-4">
                  <div className="flex items-center gap-2 text-sm text-muted-foreground">
                    <Settings className="h-4 w-4" />
                    Active Users
                  </div>
                  <p className="mt-1 text-2xl font-bold">1,429</p>
                  <p className="text-xs text-emerald-600">+3.2%</p>
                </div>
              </div>
            </div>
            <div>
              <h3 className="mb-3 text-sm font-semibold">Recent Activity</h3>
              <div className="space-y-2">
                {[
                  "New user signed up: alex@example.com",
                  "Invoice #1084 was paid ($299)",
                  "Support ticket #342 resolved",
                  "Deployment v2.4.1 completed",
                ].map((item, i) => (
                  <div
                    key={i}
                    className="rounded-md border px-3 py-2 text-sm text-muted-foreground"
                  >
                    {item}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* Copilot sidebar panel */}
      {sidebarOpen && (
        <div
          className="flex shrink-0 flex-col border-l bg-background"
          style={{ width: panelWidth }}
        >
          {/* Resize handle */}
          <div
            className="absolute left-0 top-0 z-10 flex h-full w-1 cursor-col-resize items-center justify-center hover:bg-primary/20"
            onMouseDown={handleMouseDown}
          >
            <GripVertical className="h-4 w-4 text-muted-foreground opacity-0 transition-opacity hover:opacity-100" />
          </div>

          {/* Header */}
          <div className="flex items-center justify-between border-b px-3 py-2.5">
            <div className="flex items-center gap-2">
              <Sparkles className="h-4 w-4 text-amber-500" />
              <h3 className="text-sm font-semibold">AI Copilot</h3>
            </div>
            <div className="flex items-center gap-0.5">
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={() => setIsMinimized(true)}
              >
                <Minimize2 className="h-3.5 w-3.5" />
              </Button>
              <Button
                variant="ghost"
                size="icon"
                className="h-7 w-7"
                onClick={() => setSidebarOpen(false)}
              >
                <X className="h-3.5 w-3.5" />
              </Button>
            </div>
          </div>

          {/* Context indicator */}
          <div className="flex items-center gap-2 border-b bg-muted/30 px-3 py-2">
            <Globe className="h-3 w-3 text-muted-foreground" />
            <span className="text-[11px] text-muted-foreground">
              Viewing:
            </span>
            <Badge variant="secondary" className="h-5 text-[10px]">
              Dashboard / Overview
            </Badge>
          </div>

          {/* Width indicator */}
          <div className="flex items-center justify-center border-b py-1">
            <span className="text-[10px] text-muted-foreground">
              {panelWidth}px
            </span>
          </div>

          {/* Messages */}
          <div ref={scrollRef} className="flex-1 overflow-y-auto p-3">
            <div className="space-y-3">
              {messages.map((msg) => (
                <div
                  key={msg.id}
                  className={`flex gap-2 ${msg.role === "user" ? "flex-row-reverse" : ""}`}
                >
                  <Avatar className="h-6 w-6 shrink-0">
                    <AvatarFallback className="text-[10px]">
                      {msg.role === "user" ? "U" : "AI"}
                    </AvatarFallback>
                  </Avatar>
                  <div
                    className={`max-w-[85%] rounded-lg px-3 py-2 text-xs leading-relaxed ${
                      msg.role === "user"
                        ? "bg-primary text-primary-foreground"
                        : "bg-muted"
                    }`}
                  >
                    <div className="whitespace-pre-wrap">{msg.content}</div>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Suggested prompts */}
          <div className="border-t px-3 py-2">
            <p className="mb-1.5 text-[10px] font-medium text-muted-foreground">
              Suggested
            </p>
            <div className="flex flex-wrap gap-1.5">
              {suggestedPrompts.map((prompt) => (
                <button
                  key={prompt.label}
                  onClick={() => handleSend(prompt.label)}
                  className="flex items-center gap-1 rounded-full border bg-background px-2.5 py-1 text-[11px] text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
                >
                  <prompt.icon className="h-3 w-3" />
                  {prompt.label}
                </button>
              ))}
            </div>
          </div>

          <Separator />

          {/* Input */}
          <div className="p-3">
            <form
              onSubmit={(e) => {
                e.preventDefault()
                handleSend()
              }}
              className="flex gap-2"
            >
              <Input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Ask about this page..."
                className="h-8 flex-1 text-xs"
              />
              <Button
                type="submit"
                size="icon"
                className="h-8 w-8"
                disabled={!input.trim()}
              >
                <Send className="h-3.5 w-3.5" />
              </Button>
            </form>
            <div className="mt-2 flex items-center justify-center gap-1 text-[10px] text-muted-foreground">
              <Command className="h-3 w-3" />
              <span>K to toggle copilot</span>
            </div>
          </div>
        </div>
      )}
    </div>
  )
}
